version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: geotrack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: geotrack
      POSTGRES_PASSWORD: geotrack_secret
      POSTGRES_DB: geotrack_pro
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: geotrack_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@geotrack.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
